name: kango
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: 0.26.0
  dio: 4.0.0
  logger: 1.0.0
  get_it: 7.2.0
  intl: 0.17.0
  retrofit: 2.0.1
  json_serializable: 5.0.0
  dots_indicator: 2.0.0
  json_annotation: 4.1.0
  hive_flutter: 1.1.0
  path_provider: 2.0.2
  flutter_svg: 0.22.0
  flutter_svg_provider: 0.1.9
  carousel_slider: 4.0.0
  expandable: 5.0.1
  image_picker: 0.8.3+2
  file_picker: 4.0.0
  flutter_uploader: 1.2.1
  flutter_downloader: 1.6.1
  webview_flutter: 2.0.12
  permission_handler: 8.1.4+2
  cached_network_image: 3.1.0
  url_launcher: 6.0.9
  dotted_line: 3.0.0
  clipboard: 0.1.3

# The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dependency_overrides:
  meta: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 2.0.1+1
  build_runner: 2.0.6
  hive_generator: 1.1.1
  flutter_launcher_icons: 0.9.2



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/favikon.jpg"




# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/group.png
    - asset/group2.png
    - asset/group3.png
    - asset/group967.png
    - asset/sd.png
    - asset/logo1.png
    - asset/icon_home.svg
    - asset/box.png
    - asset/sms.png
    - asset/story.png
    - asset/menu.png
    - asset/vector.png
    - asset/plus_circle.svg
    - asset/botton4.svg
    - asset/botton3.svg
    - asset/botton2.svg
    - asset/botton1.svg
    - asset/man.png
    - asset/bagraund_nbord.png
    - asset/bagraund_nbord.jpg
    - asset/union1.png
    - asset/union.png
    - asset/zakrebka.png
    - asset/navigate.png
    - asset/pen.png
    - asset/cart.png
    - asset/u_export.png
    - asset/service1.png
    - asset/azn.png
    - asset/fillials.png
    - asset/kart.png
    - asset/kuryerrr.png
    - asset/poct.png
    - asset/profilq.png
    - asset/newss.png
    - asset/tl.png
    - asset/trafik.png
    - asset/velo.svg
    - asset/loqaut.png
    - asset/melumat.png
    - asset/vill.png
    - asset/keya.png
    - asset/aznblu.png
    - asset/phone-fill.png
    - asset/data_d.png
    - asset/vektor_23.png
    - asset/dollar.png
    - asset/sale_cv.png
    - asset/raund1.png
    - asset/ok.png
    - asset/raund2.png
    - asset/mask.png
    - asset/forgot.svg
    - asset/copy.png
    - asset/favikon.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
